"""initial schema

Revision ID: 00058f3d1f5a
Revises: 
Create Date: 2026-05-27 13:35:23.377368
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '00058f3d1f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('join_token', sa.Text(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('join_token')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_label', sa.Text(), nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=False),
    sa.Column('scenario_order', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('debrief_responses',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'participant_id', name='pk_debrief')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('market_number', sa.SmallInteger(), nullable=False),
    sa.Column('scenario_id', sa.String(length=1), nullable=False),
    sa.Column('true_probability', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('stage', sa.SmallInteger(), nullable=False),
    sa.Column('b_parameter', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('q_yes', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('q_no', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('market_number BETWEEN 1 AND 4', name='ck_market_number'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'market_number', name='uq_session_market_number')
    )
    op.create_table('participant_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('join_token', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('flow_step', sa.Text(), server_default='consent', nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'participant_id'),
    sa.UniqueConstraint('join_token')
    )
    op.create_table('quiz_attempts',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('quiz_name', sa.Text(), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('final_correct', sa.Boolean(), nullable=False),
    sa.Column('raw_answers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'participant_id', 'quiz_name', name='pk_quiz_attempt')
    )
    op.create_table('risk_elicitations',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('instrument', sa.Text(), nullable=False),
    sa.Column('switch_point', sa.SmallInteger(), nullable=True),
    sa.Column('raw_choices', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'participant_id', name='pk_risk_elicitation')
    )
    op.create_table('tournament_rankings',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('total_tokens', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('prize_eur', sa.Numeric(precision=6, scale=2), server_default='0', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'participant_id', name='pk_tournament')
    )
    op.create_index('tournament_rank_idx', 'tournament_rankings', ['session_id', 'rank'], unique=False)
    op.create_table('market_resolutions',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.SmallInteger(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rng_seed', sa.Text(), nullable=True),
    sa.CheckConstraint('outcome IN (0,1)', name='ck_market_outcome'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_table('market_roles',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('role_tier', sa.Text(), nullable=False),
    sa.Column('endowment_tokens', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('final_balance', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('yes_held', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.Column('no_held', sa.Numeric(precision=12, scale=4), server_default='0', nullable=False),
    sa.CheckConstraint("role_tier IN ('uninformed','semi_informed','insider')", name='ck_role_tier'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('market_id', 'participant_id', name='pk_market_role')
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.SmallInteger(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_price', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('closing_price', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.Column('bayesian_benchmark', sa.Numeric(precision=7, scale=6), nullable=True),
    sa.CheckConstraint('round_number BETWEEN 1 AND 5', name='ck_round_number'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'round_number', name='uq_market_round')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('signal_value', sa.String(length=1), nullable=False),
    sa.Column('theta', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('posterior', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('delivered', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rng_seed', sa.Text(), nullable=True),
    sa.CheckConstraint("signal_value IN ('H','L')", name='ck_signal_value'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'participant_id', name='uq_signal_round_participant')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Text(), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_before', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('price_after', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('q_yes_after', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('q_no_after', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('yes','no')", name='ck_trade_direction'),
    sa.CheckConstraint('quantity > 0', name='ck_trade_quantity'),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('trades_participant_idx', 'trades', ['participant_id'], unique=False)
    op.create_index('trades_round_idx', 'trades', ['round_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('trades_round_idx', table_name='trades')
    op.drop_index('trades_participant_idx', table_name='trades')
    op.drop_table('trades')
    op.drop_table('signals')
    op.drop_table('rounds')
    op.drop_table('market_roles')
    op.drop_table('market_resolutions')
    op.drop_index('tournament_rank_idx', table_name='tournament_rankings')
    op.drop_table('tournament_rankings')
    op.drop_table('risk_elicitations')
    op.drop_table('quiz_attempts')
    op.drop_table('participant_sessions')
    op.drop_table('markets')
    op.drop_table('debrief_responses')
    op.drop_table('admin_actions')
    op.drop_table('sessions')
    op.drop_table('participants')
    # ### end Alembic commands ###
